=== nlsh/Kochbuch/xml/dtd_xsl/menue.dtd
<!ENTITY % TEXTFORMATIERUNGEN "FETT | ZEILENUMBRUCH | ZENTRIERT">
<!ELEMENT MENUE (MENUENAME, LINK+)>
<!ELEMENT LINK ( LINKNAME, LINKADRESSE, LINKAUSGABE)>
<!ELEMENT MENUENAME (#PCDATA )>
<!ELEMENT LINKNAME (#PCDATA | %TEXTFORMATIERUNGEN;)*>
<!ELEMENT LINKADRESSE (#PCDATA)>
<!ELEMENT LINKAUSGABE (#PCDATA)>
<!ELEMENT FETT (#PCDATA | %TEXTFORMATIERUNGEN;)*>
<!ELEMENT ZEILENUMBRUCH EMPTY>
<!ELEMENT ZENTRIERT (#PCDATA | %TEXTFORMATIERUNGEN;)*>

=== nlsh/Kochbuch/xml/menue/salateMenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "../../xml/dtd_xsl/menue.dtd">
<?xml-stylesheet type="application/xml" href="../../xml/dtd_xsl/menue.xsl"?>
<MENUE>
  <MENUENAME>Salatemen&#252;</MENUENAME>
  <LINK>
    <LINKNAME>
    <FETT>Kochbuch</FETT>
    <ZEILENUMBRUCH />
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>../../index.htm</LINKADRESSE>
    <LINKAUSGABE>_top</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>
    <FETT>Salate</FETT>
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>salateMenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Bohnensalat</LINKNAME>
    <LINKADRESSE>../rezepte/salate/bohnenSalat.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Gurkensalat</LINKNAME>
    <LINKADRESSE>../rezepte/salate/gurkenSalat.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Kartoffelsalat</LINKNAME>
    <LINKADRESSE>../rezepte/salate/kartoffelSalat.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Wei&#223;kohlsalat</LINKNAME>
    <LINKADRESSE>../rezepte/salate/weissKohlSalat.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
</MENUE>
