=== nlsh/Kochbuch/xml/dtd_xsl/menue.dtd
<!ENTITY % TEXTFORMATIERUNGEN "FETT | ZEILENUMBRUCH | ZENTRIERT">
<!ELEMENT MENUE (MENUENAME, LINK+)>
<!ELEMENT LINK ( LINKNAME, LINKADRESSE, LINKAUSGABE)>
<!ELEMENT MENUENAME (#PCDATA )>
<!ELEMENT LINKNAME (#PCDATA | %TEXTFORMATIERUNGEN;)*>
<!ELEMENT LINKADRESSE (#PCDATA)>
<!ELEMENT LINKAUSGABE (#PCDATA)>
<!ELEMENT FETT (#PCDATA | %TEXTFORMATIERUNGEN;)*>
<!ELEMENT ZEILENUMBRUCH EMPTY>
<!ELEMENT ZENTRIERT (#PCDATA | %TEXTFORMATIERUNGEN;)*>

=== nlsh/Kochbuch/xml/menue/suppenmenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "menue.dtd">
<?xml-stylesheet type="text/xsl" href="../../xml/dtd_xsl/menue.xsl" ?>
<MENUE>
  <MENUENAME>Suppen und Eint&#246;pfe Men&#252;</MENUENAME>
  <LINK>
    <LINKNAME>
    <FETT>Kochbuch</FETT>
    <ZEILENUMBRUCH />
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>../../index.htm</LINKADRESSE>
    <LINKAUSGABE>_top</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>
    <FETT>Pfannen, Suppen und Eint&#246;pfe</FETT>
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>suppenmenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Bigosch</LINKNAME>
    <LINKADRESSE>../suppen/Bigosch.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Champignonpfanne</LINKNAME>
    <LINKADRESSE>../suppen/Champignonpfanne.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Kartoffelsuppe mit Aal</LINKNAME>
    <LINKADRESSE>../suppen/Kartoffelsuppe-mit-Aal.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Kohlr&#252;beneintopf</LINKNAME>
    <LINKADRESSE>../suppen/Kohlruebeneintopf.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>K&#252;rbis- Suppe</LINKNAME>
    <LINKADRESSE>../suppen/Kurbissuppe.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Linseneintopf</LINKNAME>
    <LINKADRESSE>../suppen/Linseneintopf.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Pikante Gyros Suppe</LINKNAME>
    <LINKADRESSE>../suppen/Pikante-Gyros-Suppe.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Pizza- Suppe</LINKNAME>
    <LINKADRESSE>../suppen/Pizzasuppe.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Porree- Suppe</LINKNAME>
    <LINKADRESSE>../suppen/Porree.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Putengeschnetzeltes mit Kr&#228;uterk&#228;se</LINKNAME>
    <LINKADRESSE>../suppen/Putengeschnetzeltes-mit-Kraeuterkaese.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Rittersuppe</LINKNAME>
    <LINKADRESSE>../suppen/Rittersuppe.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Russischer Hackfleischtopf</LINKNAME>
    <LINKADRESSE>../suppen/Russischer-Hackfleischtopf.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Russische Sauerkrautsuppe</LINKNAME>
    <LINKADRESSE>../suppen/Russische-Sauerkrautsuppe.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Saftiges H&#228;hnchengulasch mit Sellerie</LINKNAME>
    <LINKADRESSE>../suppen/Saftiges-Haehnchengulasch-mit-Sellerie.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Soljanka ala Oma Christa</LINKNAME>
    <LINKADRESSE>../suppen/Gehaltvolle_Soljanka.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Weisskohleintopf</LINKNAME>
    <LINKADRESSE>../suppen/Weisskohleintopf.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Wirsingtopf mit Schweinefleisch</LINKNAME>
    <LINKADRESSE>../suppen/Wirsingtopf_mit_Schweinefleisch.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
</MENUE>

=== nlsh/Kochbuch/xml/menue/gemueseMenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "../../xml/dtd_xsl/menue.dtd">
<?xml-stylesheet type="application/xml" href="../../xml/dtd_xsl/menue.xsl"?>
<MENUE>
  <MENUENAME>Gem&#252;sebeilagen</MENUENAME>
  <LINK>
    <LINKNAME>
    <FETT>Kochbuch</FETT>
    <ZEILENUMBRUCH />
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>../../index.htm</LINKADRESSE>
    <LINKAUSGABE>_top</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>
    <FETT>Gem&#252;sebeilagen</FETT>
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>gemueseMenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Paprikagem√ºse</LINKNAME>
    <LINKADRESSE>../rezepte/gemuese/paprikaGemuese.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Rosenkohl</LINKNAME>
    <LINKADRESSE>../rezepte/gemuese/rosenKohl.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Rotkohl</LINKNAME>
    <LINKADRESSE>../rezepte/gemuese/rotKohl.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Sauerkraut</LINKNAME>
    <LINKADRESSE>../rezepte/gemuese/sauerKraut.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Spargel</LINKNAME>
    <LINKADRESSE>../rezepte/gemuese/spargel.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
</MENUE>

=== nlsh/Kochbuch/xml/menue/fleischMenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "../../xml/dtd_xsl/menue.dtd">
<?xml-stylesheet type="application/xml" href="../../xml/dtd_xsl/menue.xsl"?>
<MENUE>
  <MENUENAME>Fleischgerichte Men&#252;</MENUENAME>
  <LINK>
    <LINKNAME>
    <FETT>Kochbuch</FETT>
    <ZEILENUMBRUCH />
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>../../index.htm</LINKADRESSE>
    <LINKAUSGABE>_top</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>
    <FETT>Fleischgerichte</FETT>
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>fleischMenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Boulettenmasse</LINKNAME>
    <LINKADRESSE>../rezepte/fleisch/boulettenMasse.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Boulettentopf</LINKNAME>
    <LINKADRESSE>../rezepte/fleisch/boulettenTopf.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>H&#228;hnchengeschnetzeltes Stroganoff</LINKNAME>
    <LINKADRESSE>../rezepte/fleisch/haehnchenGeschnetzeltesStroganoff.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>K&#246;nigsberger Klopse</LINKNAME>
    <LINKADRESSE>../rezepte/fleisch/koenigsbergerKlopse.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Kohlrouladen</LINKNAME>
    <LINKADRESSE>../rezepte/fleisch/kohlrouladen.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
</MENUE>

=== nlsh/Kochbuch/xml/menue/backenMenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "../../xml/dtd_xsl/menue.dtd">
<?xml-stylesheet type="application/xml" href="../../xml/dtd_xsl/menue.xsl"?>
<MENUE>
  <MENUENAME>Backenmen&#252;</MENUENAME>
  <LINK>
    <LINKNAME>
    <FETT>Kochbuch</FETT>
    <ZEILENUMBRUCH />
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>../../index.htm</LINKADRESSE>
    <LINKAUSGABE>_top</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>
    <FETT>Backen</FETT>
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>backenMenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Ananas- Mandarinen- Torte</LINKNAME>
    <LINKADRESSE>../rezepte/backen/ananasMandarinenTorte.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Biskuitboden</LINKNAME>
    <LINKADRESSE>../rezepte/backen/biskuitBoden.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>K&#228;setorte ohne Boden</LINKNAME>
    <LINKADRESSE>../rezepte/backen/kaeseOhneBoden.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Kokosmakronen</LINKNAME>
    <LINKADRESSE>../rezepte/backen/kokosMakronen.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Kokospl&#228;tzchen</LINKNAME>
    <LINKADRESSE>../rezepte/backen/kokosPlaetzchen.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Philadelphie- K&#228;se- Torte</LINKNAME>
    <LINKADRESSE>../rezepte/backen/philadelphiaKaeseTorte.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Raffaello Torte</LINKNAME>
    <LINKADRESSE>../rezepte/backen/raffaelloTorte.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Rotk&#228;ppchenkuchen</LINKNAME>
    <LINKADRESSE>../rezepte/backen/rotkaepchenKuchen.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Sprudelkuchen</LINKNAME>
    <LINKADRESSE>../rezepte/backen/sprudelKuchen.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Stachelbeer- Butterkeks- Kuchen</LINKNAME>
    <LINKADRESSE>../rezepte/backen/stachelbeerButterkeksKuchen.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Waffeln</LINKNAME>
    <LINKADRESSE>../rezepte/backen/waffeln.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
</MENUE>

=== nlsh/Kochbuch/xml/menue/hauptmenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "menue.dtd">
<?xml-stylesheet type="text/xsl" href="menue.xsl"?>
<MENUE>
  <MENUENAME>Hauptmen&#252;</MENUENAME>
  <LINK>
    <LINKNAME>
    <FETT>Kochbuch</FETT>
    <ZEILENUMBRUCH />
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>../index.htm</LINKADRESSE>
    <LINKAUSGABE>_top</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Backen</LINKNAME>
    <LINKADRESSE>backenmenuemenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>im Backofen</LINKNAME>
    <LINKADRESSE>imbackofenmenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Fleischgerichte</LINKNAME>
    <LINKADRESSE>fleischgerichtemenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Gem&#252;sebeilagen</LINKNAME>
    <LINKADRESSE>gemuesebeilagenmenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Salate</LINKNAME>
    <LINKADRESSE>salatemenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Pfannen, Suppen und Eint&#246;pfe</LINKNAME>
    <LINKADRESSE>suppenmenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Nudelgerichte</LINKNAME>
    <LINKADRESSE>nudelmenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
    <LINK>
    <LINKNAME>auf dem Grill</LINKNAME>
    <LINKADRESSE>grill.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
</MENUE>

=== nlsh/Kochbuch/xml/menue/nudelmenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "../../xml/dtd_xsl/menue.dtd">
<?xml-stylesheet type="application/xml" href="../../xml/dtd_xsl/menue.xsl"?>sl/menue.xsl" ?>
<MENUE>
  <MENUENAME>Nudelmen&#252;</MENUENAME>
  <LINK>
    <LINKNAME>
    <FETT>Kochbuch</FETT>
    <ZEILENUMBRUCH />
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>../../index.htm</LINKADRESSE>
    <LINKAUSGABE>_top</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>
    <FETT>Nudelgerichte</FETT>
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>nudelMenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Garnelen in Sahnesauce</LINKNAME>
    <LINKADRESSE>../rezepte/nudeln/garnelenMitSahneSauce.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
</MENUE>

=== nlsh/Kochbuch/xml/menue/hauptMenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "../dtd_xls/dtd_xsl/menue.dtd">
<?xml-stylesheet type="application/xml" href="../dtd_xsl/menue.xsl"?>
<MENUE>
  <MENUENAME>Hauptmen&#252;</MENUENAME>
  <LINK>
    <LINKNAME>
    <FETT>Kochbuch</FETT>
    <ZEILENUMBRUCH />
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>../../index.htm</LINKADRESSE>
    <LINKAUSGABE>_top</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Backen</LINKNAME>
    <LINKADRESSE>backenMenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>im Backofen</LINKNAME>
    <LINKADRESSE>backofenMenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Fleischgerichte</LINKNAME>
    <LINKADRESSE>fleischMenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Fischgerichte</LINKNAME>
    <LINKADRESSE>fischMenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Gem&#252;sebeilagen</LINKNAME>
    <LINKADRESSE>gemueseMenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Salate</LINKNAME>
    <LINKADRESSE>salateMenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Pfannen, Suppen und Eint&#246;pfe</LINKNAME>
    <LINKADRESSE>suppenMenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Nudelgerichte</LINKNAME>
    <LINKADRESSE>nudelMenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
    <LINK>
    <LINKNAME>auf dem Grill</LINKNAME>
    <LINKADRESSE>grillMenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
</MENUE>

=== nlsh/Kochbuch/xml/menue/grillmenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "menue.dtd">
<?xml-stylesheet type="text/xsl" href="../../xml/dtd_xsl/menue.xsl" ?>
<MENUE>
 <MENUENAME>Grillmen&#252;</MENUENAME>
 <LINK>
  <LINKNAME>
  <FETT>Kochbuch</FETT>
  <ZEILENUMBRUCH />
  <ZEILENUMBRUCH />&#160;</LINKNAME>
  <LINKADRESSE>../../index.htm</LINKADRESSE>
  <LINKAUSGABE>_top</LINKAUSGABE>
 </LINK>
 <LINK>
  <LINKNAME>
  <FETT>Auf dem Grill</FETT>
  <ZEILENUMBRUCH />&#160;</LINKNAME>
  <LINKADRESSE>grillmenue.xml</LINKADRESSE>
  <LINKAUSGABE>Inhalt</LINKAUSGABE>
 </LINK>
 <LINK>
  <LINKNAME>Grillschnitte</LINKNAME>
  <LINKADRESSE>../rezepte/grill/grillschnitte.xml</LINKADRESSE>
  <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
 </LINK>
</MENUE>
