=== nlsh/Kochbuch/xml/dtd_xsl/menue.dtd
<!ENTITY % TEXTFORMATIERUNGEN "FETT | ZEILENUMBRUCH | ZENTRIERT">
<!ELEMENT MENUE (MENUENAME, LINK+)>
<!ELEMENT LINK ( LINKNAME, LINKADRESSE, LINKAUSGABE)>
<!ELEMENT MENUENAME (#PCDATA )>
<!ELEMENT LINKNAME (#PCDATA | %TEXTFORMATIERUNGEN;)*>
<!ELEMENT LINKADRESSE (#PCDATA)>
<!ELEMENT LINKAUSGABE (#PCDATA)>
<!ELEMENT FETT (#PCDATA | %TEXTFORMATIERUNGEN;)*>
<!ELEMENT ZEILENUMBRUCH EMPTY>
<!ELEMENT ZENTRIERT (#PCDATA | %TEXTFORMATIERUNGEN;)*>

=== nlsh/Kochbuch/xml/menue/salatemenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "menue.dtd">
<?xml-stylesheet type="text/xsl" href="../../xml/dtd_xsl/menue.xsl" ?>
<MENUE>
  <MENUENAME>Salatemen&#252;</MENUENAME>
  <LINK>
    <LINKNAME>
    <FETT>Kochbuch</FETT>
    <ZEILENUMBRUCH />
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>../../index.htm</LINKADRESSE>
    <LINKAUSGABE>_top</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>
    <FETT>Salate</FETT>
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>salatemenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Bohnensalat</LINKNAME>
    <LINKADRESSE>../salate/Bohnensalat.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Gurkensalat</LINKNAME>
    <LINKADRESSE>../salate/Gurkensalat.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Kartoffelsalat</LINKNAME>
    <LINKADRESSE>../salate/Kartoffelsalat.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Wei&#223;kohlsalat</LINKNAME>
    <LINKADRESSE>../salate/Weisskohlsalat.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
</MENUE>

=== nlsh/Kochbuch/xml/menue/backenmenuemenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "menue.dtd">
<?xml-stylesheet type="text/xsl" href="../../xml/dtd_xsl/menue.xsl" ?>
<MENUE>
  <MENUENAME>Backenmen&#252;</MENUENAME>
  <LINK>
    <LINKNAME>
    <FETT>Kochbuch</FETT>
    <ZEILENUMBRUCH />
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>../../index.htm</LINKADRESSE>
    <LINKAUSGABE>_top</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>
    <FETT>Backen</FETT>
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>backenmenuemenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Ananas- Mandarinen- Torte</LINKNAME>
    <LINKADRESSE>../rezepte/backen/Ananas-Mandarinen-Torte.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Biskuitboden</LINKNAME>
    <LINKADRESSE>../rezepte/backen/Biskuitboden.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>K&#228;setorte ohne Boden</LINKNAME>
    <LINKADRESSE>../rezepte/backen/Kaeseohneboden.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Kokosmakronen</LINKNAME>
    <LINKADRESSE>../rezepte/backen/Kokosmakronen.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Kokospl&#228;tzchen</LINKNAME>
    <LINKADRESSE>../rezepte/backen/Kokosplaetzchen.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Philadelphie- K&#228;se- Torte</LINKNAME>
    <LINKADRESSE>../rezepte/backen/Philadelphia-Kaese-Torte.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Raffaello Torte</LINKNAME>
    <LINKADRESSE>../rezepte/backen/Raffaello-Torte.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Rotk&#228;ppchenkuchen</LINKNAME>
    <LINKADRESSE>../rezepte/backen/Rotkaepchenkuchen.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Sprudelkuchen</LINKNAME>
    <LINKADRESSE>../rezepte/backen/Sprudelkuchen.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Stachelbeer- Butterkeks- Kuchen</LINKNAME>
    <LINKADRESSE>../rezepte/backen/Stachelbeer_Butterkeks_Kuchen.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Waffeln</LINKNAME>
    <LINKADRESSE>../rezepte/backen/Waffeln.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
</MENUE>

=== nlsh/Kochbuch/xml/menue/fischMenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "../../xml/dtd_xsl/menue.dtd">
<?xml-stylesheet type="application/xml" href="../../xml/dtd_xsl/menue.xsl"?>
<MENUE>
 <MENUENAME>Fischmen&#252;</MENUENAME>
 <LINK>
  <LINKNAME>
  <FETT>Kochbuch</FETT>
  <ZEILENUMBRUCH />
  <ZEILENUMBRUCH />&#160;</LINKNAME>
  <LINKADRESSE>../../index.htm</LINKADRESSE>
  <LINKAUSGABE>_top</LINKAUSGABE>
 </LINK>
 <LINK>
  <LINKNAME>
  <FETT>Fischgerichte</FETT>
  <ZEILENUMBRUCH />&#160;</LINKNAME>
  <LINKADRESSE>fischMenue.xml</LINKADRESSE>
  <LINKAUSGABE>Inhalt</LINKAUSGABE>
 </LINK>
 <LINK>
  <LINKNAME>Karpfen in Bierso√üe</LINKNAME>
  <LINKADRESSE>../rezepte/fisch/karpfenInBiersosse.xml</LINKADRESSE>
  <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
 </LINK>
</MENUE>

=== nlsh/Kochbuch/xml/menue/imbackofenmenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "menue.dtd">
<?xml-stylesheet type="text/xsl" href="../../xml/dtd_xsl/menue.xsl" ?>
<MENUE>
  <MENUENAME>Im Backofen Men&#252;</MENUENAME>
  <LINK>
    <LINKNAME>
    <FETT>Kochbuch</FETT>
    <ZEILENUMBRUCH />
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>../../index.htm</LINKADRESSE>
    <LINKAUSGABE>_top</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>
    <FETT>im Backofen</FETT>
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>imbackofenmenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Backofensuppe</LINKNAME>
    <LINKADRESSE>../rezepte/imbackofen/Backofensuppe.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Eine Karre Mist</LINKNAME>
    <LINKADRESSE>../rezepte/imbackofen/Eine-Karre-Mist.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>H&#228;hnchen portugiesisch</LINKNAME>
    <LINKADRESSE>../rezepte/imbackofen/Haehnchen-portugiesisch.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Kaukasisches Reiterfleisch</LINKNAME>
    <LINKADRESSE>../rezepte/imbackofen/Kaukasisches-Reiterfleisch.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Paprikapfanne mit Schweinekamm</LINKNAME>
    <LINKADRESSE>../rezepte/imbackofen/Paprikapfanne-mit-Schweinekamm.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>R&#228;uberhachbraten</LINKNAME>
    <LINKADRESSE>../rezepte/imbackofen/Raeuberhackbraten.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Saftige Schnitzel- Pizza</LINKNAME>
    <LINKADRESSE>../rezepte/imbackofen/Saftige-Schnitzel-Pizza.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
</MENUE>

=== nlsh/Kochbuch/xml/menue/fleischgerichtemenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "menue.dtd">
<?xml-stylesheet type="text/xsl" href="../../xml/dtd_xsl/menue.xsl" ?>
<MENUE>
  <MENUENAME>Fleischgerichte Men&#252;</MENUENAME>
  <LINK>
    <LINKNAME>
    <FETT>Kochbuch</FETT>
    <ZEILENUMBRUCH />
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>../../index.htm</LINKADRESSE>
    <LINKAUSGABE>_top</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>
    <FETT>Fleischgerichte</FETT>
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>fleischgerichtemenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Boulettenmasse</LINKNAME>
    <LINKADRESSE>../rezepte/fleischgerichte/Boulettenmasse.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Boulettentopf</LINKNAME>
    <LINKADRESSE>../rezepte/fleischgerichte/Boulettentopf.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>H&#228;hnchengeschnetzeltes Stroganoff</LINKNAME>
    <LINKADRESSE>../rezepte/fleischgerichte/Haehnchengeschnetzeltes-Stroganoff.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>K&#246;nigsberger Klopse</LINKNAME>
    <LINKADRESSE>../rezepte/fleischgerichte/Koenigsbergerklopse.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Kohlrouladen</LINKNAME>
    <LINKADRESSE>../rezepte/fleischgerichte/Kohlrouladen.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
</MENUE>

=== nlsh/Kochbuch/xml/menue/backofenMenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "../../xml/dtd_xsl/menue.dtd">
<?xml-stylesheet type="application/xml" href="../../xml/dtd_xsl/menue.xsl"?>
<MENUE>
  <MENUENAME>Im Backofen Men&#252;</MENUENAME>
  <LINK>
    <LINKNAME>
    <FETT>Kochbuch</FETT>
    <ZEILENUMBRUCH />
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>../../index.htm</LINKADRESSE>
    <LINKAUSGABE>_top</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>
    <FETT>im Backofen</FETT>
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>backofenMenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Backofensuppe</LINKNAME>
    <LINKADRESSE>../rezepte/backofen/backOfenSuppe.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Eine Karre Mist</LINKNAME>
    <LINKADRESSE>../rezepte/backofen/eineKarreMist.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>H&#228;hnchen portugiesisch</LINKNAME>
    <LINKADRESSE>../rezepte/backofen/haehnchenPortugiesisch.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Kaukasisches Reiterfleisch</LINKNAME>
    <LINKADRESSE>../rezepte/backofen/kaukasischesReiterFleisch.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Paprikapfanne mit Schweinekamm</LINKNAME>
    <LINKADRESSE>../rezepte/backofen/paprikaPfanneMitSchweineKamm.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>R&#228;uberhachbraten</LINKNAME>
    <LINKADRESSE>../rezepte/backofen/raeuberHackBraten.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Saftige Schnitzel- Pizza</LINKNAME>
    <LINKADRESSE>../rezepte/backofen/saftigeSchnitzelPizza.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
</MENUE>

=== nlsh/Kochbuch/xml/menue/gemuesebeilagenmenue.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "menue.dtd">
<?xml-stylesheet type="text/xsl" href="../../xml/dtd_xsl/menue.xsl" ?>
<MENUE>
  <MENUENAME>Gem&#252;sebeilagen</MENUENAME>
  <LINK>
    <LINKNAME>
    <FETT>Kochbuch</FETT>
    <ZEILENUMBRUCH />
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>../../index.htm</LINKADRESSE>
    <LINKAUSGABE>_top</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>
    <FETT>Gem&#252;sebeilagen</FETT>
    <ZEILENUMBRUCH />&#160;</LINKNAME>
    <LINKADRESSE>gemuesebeilagenmenue.xml</LINKADRESSE>
    <LINKAUSGABE>Inhalt</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Paprikagem√ºse</LINKNAME>
    <LINKADRESSE>../Gemuesebeilagen/PaprikaGemuesel.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Rosenkohl</LINKNAME>
    <LINKADRESSE>../Gemuesebeilagen/Rosenkohl.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Rotkohl</LINKNAME>
    <LINKADRESSE>../Gemuesebeilagen/Rotkohl.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Sauerkraut</LINKNAME>
    <LINKADRESSE>../Gemuesebeilagen/Sauerkraut.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
  <LINK>
    <LINKNAME>Spargel</LINKNAME>
    <LINKADRESSE>../Gemuesebeilagen/Spargel.xml</LINKADRESSE>
    <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
  </LINK>
</MENUE>

=== nlsh/Kochbuch/xml/menue/grill.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MENUE SYSTEM "menue.dtd">
<?xml-stylesheet type="text/xsl" href="menue.xsl" ?>
<MENUE>
 <MENUENAME>Grillmen&#252;</MENUENAME>
 <LINK>
  <LINKNAME>
  <FETT>Kochbuch</FETT>
  <ZEILENUMBRUCH />
  <ZEILENUMBRUCH />&#160;</LINKNAME>
  <LINKADRESSE>../index.htm</LINKADRESSE>
  <LINKAUSGABE>_top</LINKAUSGABE>
 </LINK>
 <LINK>
  <LINKNAME>
  <FETT>Auf dem Grill</FETT>
  <ZEILENUMBRUCH />&#160;</LINKNAME>
  <LINKADRESSE>grill.xml</LINKADRESSE>
  <LINKAUSGABE>Inhalt</LINKAUSGABE>
 </LINK>
 <LINK>
  <LINKNAME>Grillschnitte</LINKNAME>
  <LINKADRESSE>../grill/grillschnitte.xml</LINKADRESSE>
  <LINKAUSGABE>Hauptfenster</LINKAUSGABE>
 </LINK>
</MENUE>
