=== nlsh/Kochbuch/xml/dtd_xsl/rezept.dtd
<!ENTITY % TEXTFORMATIERUNGEN "FETT | ZEILENUMBRUCH | ZENTRIERT">
<!ENTITY % GRAFIK "BILD">
<!ELEMENT REZEPT (REZEPTNAME, KATEGORIE, AUTOR, BEWERTUNG, ANZAHLPERSONEN, ZUBEREITUNGSZEIT, ZUTATEN, ZUBEREITUNG )>
<!ELEMENT REZEPTNAME (#PCDATA)>
<!ELEMENT KATEGORIE (#PCDATA)>
<!ELEMENT AUTOR (#PCDATA)>
<!ELEMENT BEWERTUNG (#PCDATA)>
<!ELEMENT ANZAHLPERSONEN (#PCDATA)>
<!ELEMENT ZUBEREITUNGSZEIT (#PCDATA)>
<!ELEMENT ZUTATEN (ZUTAT)+ >
<!ELEMENT ZUTAT (#PCDATA)>
<!ELEMENT ZUBEREITUNG (ITEM  | %GRAFIK;)+>
<!ELEMENT ITEM (#PCDATA | %TEXTFORMATIERUNGEN; | %GRAFIK;)*>
<!ELEMENT FETT (#PCDATA | %TEXTFORMATIERUNGEN;)*>
<!ELEMENT ZEILENUMBRUCH EMPTY>
<!ELEMENT ZENTRIERT (#PCDATA | %TEXTFORMATIERUNGEN; | %GRAFIK;)*>
<!ELEMENT BILD (BILDURL, BILDNAME, BILDHOHE, BILDBREITE, BILDBESCHREIBUNG)>
<!ELEMENT BILDURL (#PCDATA)>
<!ELEMENT BILDNAME (#PCDATA)>
<!ELEMENT BILDHOHE (#PCDATA)>
<!ELEMENT BILDBREITE (#PCDATA)>
<!ELEMENT BILDBESCHREIBUNG (#PCDATA)>

=== nlsh/Kochbuch/xml/rezepte/suppen/saftigesHaehnchenGulaschMitSellerie.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE REZEPT SYSTEM "../../dtd_xsl/rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Saftiges H&#228;hnchengulasch mit Sellerie</REZEPTNAME>
  <KATEGORIE>Suppen</KATEGORIE>
  <AUTOR></AUTOR>
  <BEWERTUNG>*****</BEWERTUNG>
  <ANZAHLPERSONEN>4</ANZAHLPERSONEN>
  <ZUBEREITUNGSZEIT>50 Minuten</ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>400 g H&#228;hnchenbrustfilet</ZUTAT>
    <ZUTAT>2 kleine Zwiebeln</ZUTAT>
    <ZUTAT>400 g Stangensellerie</ZUTAT>
    <ZUTAT>&#189; Bund Lauchzwiebeln</ZUTAT>
    <ZUTAT>1 - 2 EL. Butter, Salz</ZUTAT>
    <ZUTAT>1 Dose ( 425 ml) Aprikosen</ZUTAT>
    <ZUTAT>2 EL. &#214;l, getrockneter Chili</ZUTAT>
    <ZUTAT>1 EL. Tomatenmark</ZUTAT>
    <ZUTAT>1 EL. Mehl</ZUTAT>
    <ZUTAT>1 EL. Pfefferk&#246;rner</ZUTAT>
    <ZUTAT>4 EL. Ketchup</ZUTAT>
    <ZUTAT>100 g Schlagsahne</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Filet w&#252;rfeln, Zwiebeln halbieren, Sellerie und Lauchzwiebeln in
    St&#252;cke schneiden</ITEM>
    <ITEM>Butter erhitzen, Gem&#252;se darin ca. 2 Minuten d&#252;nsten, salzen, mit 200
    ml Wasser abl&#246;schen und kurz aufkochen lassen.</ITEM>
    <ITEM>Aprikosen abtropfen lassen und in St&#252;cke schneiden.</ITEM>
    <ITEM>Filet und Zwiebeln im &#214;l anbraten, w&#252;rzen, Tomatenmark zuf&#252;gen
    und mit anschwitzen, mit Mehl best&#228;uben, mit &#189; Liter Wasser abl&#246;schen,
    Ketchup hinzuf&#252;gen und 30 Minuten schmoren.</ITEM>
    <ITEM>Gem&#252;se mit Fl&#252;ssigkeit, Pfirsichen, Pfeffer und Sahne in die
    So&#223;e geben, aufkochen lassen und erneut abschmecken.</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/gemuese/rotKohl.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE REZEPT SYSTEM "../../dtd_xsl/rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Rotkohl</REZEPTNAME>
  <KATEGORIE>Gem&#252;sebeilagen</KATEGORIE>
  <AUTOR>Mei&#223;ner, Christa</AUTOR>
  <BEWERTUNG>*****</BEWERTUNG>
  <ANZAHLPERSONEN>3</ANZAHLPERSONEN>
  <ZUBEREITUNGSZEIT>45 Minuten</ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>1 mittelgro&#223;en Rotkohl</ZUTAT>
    <ZUTAT>anderthalb Tassen Apfelsaft {optional Wasser}</ZUTAT>
    <ZUTAT>10 Essl&#246;ffel 10%- iger Essig</ZUTAT>
    <ZUTAT>1 Essl&#246;ffel Salz</ZUTAT>
    <ZUTAT>4 Essl&#246;ffel Zucker</ZUTAT>
    <ZUTAT>1 mittelgro&#223;e Zwiebel, die ganz gelassen wird.</ZUTAT>
    <ZUTAT>4 Nelken</ZUTAT>
    <ZUTAT>1 Apfel, Boskop</ZUTAT>
    <ZUTAT>&#189; Essl&#246;ffel Schmalz {optional Margarine}</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Den Kohl vierteln, vom Strunk befreien und fein schneiden.</ITEM>
    <ITEM>Die Zutaten werden mit dem Kohl
    <FETT>20 Minuten&#160;</FETT>gekocht.</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/grill/grillSchnitte.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE REZEPT SYSTEM "../../dtd_xsl/rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/rezepte.xsl" ?>
<REZEPT>
 <REZEPTNAME>Grillschnitte</REZEPTNAME>
 <KATEGORIE>Auf dem Grill</KATEGORIE>
 <AUTOR>Anke Herrmann</AUTOR>
 <BEWERTUNG>*****</BEWERTUNG>
 <ANZAHLPERSONEN></ANZAHLPERSONEN>
 <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
 <ZUTATEN>
  <ZUTAT>Gehacktes, fertig gew&#252;rzt (siehe Boulettenmasse unter Fleischgerichte)</ZUTAT>
  <ZUTAT>Brot</ZUTAT>
 </ZUTATEN>
 <ZUBEREITUNG>
  <ITEM>Auf dem Brot das Gehaktes auftragen und dann auf dem Grill beidseitig grillen.</ITEM>
 </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/Gemuesebeilagen/Rosenkohl.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE REZEPT SYSTEM "../Rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../Rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Rosenkohl</REZEPTNAME>
  <KATEGORIE>Gem&#252;sebeilagen</KATEGORIE>
  <AUTOR>Mei&#223;ner, Christa</AUTOR>
  <BEWERTUNG>*****</BEWERTUNG>
  <ANZAHLPERSONEN>2</ANZAHLPERSONEN>
  <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>750 g Rosenkohl</ZUTAT>
    <ZUTAT>2 Teel&#246;ffel Salz</ZUTAT>
    <ZUTAT>geriebene Muskatnuss, nach Geschmack</ZUTAT>
    <ZUTAT>1 &#189; Essl&#246;ffel Butter</ZUTAT>
    <ZUTAT>Wasser</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Den Rosenkohl putzen, an der Basis kreuzweise einschneiden, in einen Topf geben
    und soviel Wasser zuf&#252;gen, dass die R&#246;schen gerade bedeckt sind.</ITEM>
    <ITEM>Das Salz zugeben und den Rosenkohl zum Kochen bringen. Kochzeit zwischendurch
    &#252;berpr&#252;fen, abh&#228;ngig von der Gr&#246;&#223;e der R&#246;schen,
    zwischen 15- 20 Minuten.</ITEM>
    <ITEM>Rosenkohl durch ein Sieb abgie&#223;en. Wasser wegsch&#252;tten!</ITEM>
    <ITEM>Die Butter in eine Pfanne geben, br&#228;unen, und die R&#246;schen darin
    schwenken.</ITEM>
    <ITEM>Das Muskat kann zur Geschmacksbildung jetzt mit untergeschwenkt werden.</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/backen/kaeseOhneBoden.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE REZEPT SYSTEM "../../dtd_xsl/rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>K&#228;setorte ohne Boden</REZEPTNAME>
  <KATEGORIE>Backen</KATEGORIE>
  <AUTOR>unbekannt</AUTOR>
  <BEWERTUNG></BEWERTUNG>
  <ANZAHLPERSONEN></ANZAHLPERSONEN>
  <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>1 kg Quark</ZUTAT>
    <ZUTAT>6- 8 Eier</ZUTAT>
    <ZUTAT>4 Essl&#246;ffel Gries</ZUTAT>
    <ZUTAT>2 Essl&#246;ffel Kartoffelmehl ( Weizenin)</ZUTAT>
    <ZUTAT>&#190; P&#228;ckchen Backpulver</ZUTAT>
    <ZUTAT>250 g Zucker</ZUTAT>
    <ZUTAT>&#188; Flasche Rum- Aroma</ZUTAT>
    <ZUTAT>250 g Fett</ZUTAT>
    <ZUTAT>1 Zitrone</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Quark, Eigelb, Grie&#223;, Kartoffelmehl, Bachpulver, Zitronesaft, Zucker und geriebene
    Zitronenschale miteinander verr&#252;hren</ITEM>
    <ITEM>Fett fl&#252;ssig machen und dazugeben</ITEM>
    <ITEM>Eiwei&#223; zu Schnee schlagen und unter die Masse heben</ITEM>
    <ITEM>alles in eine Springform geben und im Ofen ca. 1 h bei 175&#186; Celsius
    backen</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/backofen/raeuberHackBraten.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE REZEPT SYSTEM "../../dtd_xsl/rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>R&#228;uberhackbraten</REZEPTNAME>
  <KATEGORIE>Backofen</KATEGORIE>
  <AUTOR></AUTOR>
  <BEWERTUNG></BEWERTUNG>
 <ANZAHLPERSONEN></ANZAHLPERSONEN>
 <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>2 altbackene Br&#246;tchen</ZUTAT>
    <ZUTAT>200 g junger Gouda</ZUTAT>
    <ZUTAT>4 Zwiebeln</ZUTAT>
    <ZUTAT>3 Knoblauchzehen</ZUTAT>
    <ZUTAT>2 rote Paprikaschoten</ZUTAT>
    <ZUTAT>1 Glas ( 360 g) Champignons</ZUTAT>
    <ZUTAT>5 Essl&#246;ffel Speise&#246;l</ZUTAT>
    <ZUTAT>1,2 kg Gehacktes ( halb Rind-, halb Schweinefleisch)</ZUTAT>
    <ZUTAT>4 Eier</ZUTAT>
    <ZUTAT>1 Essl&#246;ffel Paprika edels&#252;&#223;</ZUTAT>
    <ZUTAT>1 Essl&#246;ffel Paprika scharf</ZUTAT>
    <ZUTAT>Salz</ZUTAT>
    <ZUTAT>frisch gemahlener Pfeffer</ZUTAT>
    <ZUTAT>300 g durchwachsener Speck</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Br&#246;tchen in kaltem Wasser einweichen. K&#228;se w&#252;rfeln. Zwiebeln und
    Knoblauch abziehen und fein hacken.</ITEM>
    <ITEM>Paprikaschoten vierteln, entkernen, die wei&#223;en Scheidew&#228;nde entfernen,
    Paprika waschen und in kleine W&#252;rfel schneiden. Pilze abtropfen lassen und in feine
    Scheiben schneiden.</ITEM>
    <ITEM>&#214;l erhitzen, Zwiebel- und Knoblauchw&#252;rfel darin d&#252;nsten.
    Paprikaw&#252;rfel hinzuf&#252;gen, mit and&#252;nsten. Pilze und K&#228;se
    unterheben.</ITEM>
    <ITEM>Br&#246;tchen gut ausdr&#252;cken. Alle Zutaten mit dem Hackfleisch und Eiern zu
    einem Teig verarbeiten, mit den Gew&#252;rzen abschmecken.</ITEM>
    <ITEM>Den Speck in Scheiben schneiden. Die Hackfleischmasse zu einem Klo&#223; formen, die
    Speckscheiben darauflegen, mit K&#252;chengarn zusammenbinden und in eine Fettfangschale
    legen.</ITEM>
    <ITEM>Die Fettfangschale in den Backofen schieben. Nach und nach etwas Wasser
    hinzuf&#252;gen</ITEM>
    <ITEM>Bratzeit: 75 min
    <ZEILENUMBRUCH />
    <ZEILENUMBRUCH />Ober-/ Unterhitze: etwa 180 &#186; C ( vorgeheizt)
    <ZEILENUMBRUCH />Hei&#223;luft: etwa 160 &#186; C ( nicht vorgeheizt)
    <ZEILENUMBRUCH />Gas: etwa Stufe 3 ( vorgeheizt)</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/suppen/Russische-Sauerkrautsuppe.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE REZEPT SYSTEM "../Rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../Rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Russische Sauerkrautsuppe</REZEPTNAME>
  <KATEGORIE>Suppen</KATEGORIE>
  <AUTOR></AUTOR>
  <BEWERTUNG>*****</BEWERTUNG>
 <ANZAHLPERSONEN></ANZAHLPERSONEN>
 <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>750 g Hochrippe vom Rind</ZUTAT>
    <ZUTAT>1 Teel&#246;ffel Salz</ZUTAT>
    <ZUTAT>4 Zwiebeln</ZUTAT>
    <ZUTAT>1 Bund Suppengr&#252;n</ZUTAT>
    <ZUTAT>1 Lorbeerblatt</ZUTAT>
    <ZUTAT>2 Essl&#246;ffel Butter</ZUTAT>
    <ZUTAT>1 Knoblauchzehe</ZUTAT>
    <ZUTAT>1 kg Sauerkraut</ZUTAT>
    <ZUTAT>1 Essl&#246;ffel Paprikapulver, edels&#252;&#223;</ZUTAT>
    <ZUTAT>1 kg Tomaten</ZUTAT>
    <ZUTAT>2 gr&#252;ne Paprikaschoten</ZUTAT>
    <ZUTAT>400 g ger&#228;ucherte W&#252;rstchen</ZUTAT>
    <ZUTAT>&#189; Teel&#246;ffel Zucker</ZUTAT>
    <ZUTAT>je 1 Prise Cayennepfeffer und frisch gemahlener schwarzer Pfeffer</ZUTAT>
    <ZUTAT>150 g saure Sahne</ZUTAT>
    <ZUTAT>4 Essl&#246;ffel gehackte Petersilie</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Das Fleisch waschen und in 2 l Salzwasser zum kochen bringen.</ITEM>
    <ITEM>Die Zwiebeln sch&#228;len. Das Suppengr&#252;n waschen, kleinschneiden, mit 1
    Zwiebel und dem Lorbeerblatt in die Bouillon geben und diese zugedeckt 1 &#189; h kochen
    lassen.</ITEM>
    <ITEM>Die &#252;brigen Zwiebeln w&#252;rfeln.</ITEM>
    <ITEM>Die Butter zerlassen, die Zwiebeln darin anbraten. Den Knoblauch dazudr&#252;cken,
    mit dem Sauerkraut und dem Paprikapulver mischen.</ITEM>
    <ITEM>Die Tomaten h&#228;uten und zerschneiden. Die Paprikaschoten waschen, putzen,
    w&#252;rfeln und mit den Tomaten unter das Kraut mischen.</ITEM>
    <ITEM>Die Bouillon durchseihen, zum Kraut gie&#223;en und alles zugedeckt weitere 25
    Minuten leicht kochen lassen.</ITEM>
    <ITEM>Das Fleisch w&#252;rfeln. Die W&#252;rste in Scheiben schneiden. Beides in die Suppe
    geben.</ITEM>
    <ITEM>Die Suppe mit dem Zucker, dem Cayennepfeffer und dem schwarzen Pfeffer abschmecken.
    Mit der sauren Sahne und der Petersilie servieren.</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/imbackofen/Kaukasisches-Reiterfleisch.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE REZEPT SYSTEM "../Rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/Rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Kaukasisches Reiterfleisch</REZEPTNAME>
  <KATEGORIE>Backofen</KATEGORIE>
  <AUTOR></AUTOR>
  <BEWERTUNG></BEWERTUNG>
 <ANZAHLPERSONEN></ANZAHLPERSONEN>
 <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>8 Scheiben Kamm (pro Person rechnet man 2 Scheiben)</ZUTAT>
    <ZUTAT>Salz, Pfeffer, Senf, Zwiebeln</ZUTAT>
    <ZUTAT>1 Glas Letscho</ZUTAT>
    <ZUTAT>Chili-Pulver</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Kammscheiben mit Salz, Pfeffer und Senf w&#252;rzen.</ITEM>
    <ITEM>Die Kammscheiben in einer h&#246;heren Auflaufform hochkant schichten. Zwischen den
    einzelnen Scheiben Zwiebelringe legen.</ITEM>
    <ITEM>Alles mit etwas Chili- Pulver bestreuen und Letscho dar&#252;bergeben.</ITEM>
    <ITEM>Die Form mit Deckel in die R&#246;hre schieben und &#189; Stunde bei Mittelhitze
    garen.</ITEM>
    <ITEM>Vor dem Servieren nochmals &#188; bis &#189; Stunde in der R&#246;hre bei
    Mittelhitze garen.</ITEM>
    <ITEM>Dazu kann &#252;berbackenes Toastbrot gereicht werden. Auch Reis passt dazu.</ITEM>
  </ZUBEREITUNG>
</REZEPT>
