=== nlsh/Kochbuch/xml/dtd_xsl/rezept.dtd
<!ENTITY % TEXTFORMATIERUNGEN "FETT | ZEILENUMBRUCH | ZENTRIERT">
<!ENTITY % GRAFIK "BILD">
<!ELEMENT REZEPT (REZEPTNAME, KATEGORIE, AUTOR, BEWERTUNG, ANZAHLPERSONEN, ZUBEREITUNGSZEIT, ZUTATEN, ZUBEREITUNG )>
<!ELEMENT REZEPTNAME (#PCDATA)>
<!ELEMENT KATEGORIE (#PCDATA)>
<!ELEMENT AUTOR (#PCDATA)>
<!ELEMENT BEWERTUNG (#PCDATA)>
<!ELEMENT ANZAHLPERSONEN (#PCDATA)>
<!ELEMENT ZUBEREITUNGSZEIT (#PCDATA)>
<!ELEMENT ZUTATEN (ZUTAT)+ >
<!ELEMENT ZUTAT (#PCDATA)>
<!ELEMENT ZUBEREITUNG (ITEM  | %GRAFIK;)+>
<!ELEMENT ITEM (#PCDATA | %TEXTFORMATIERUNGEN; | %GRAFIK;)*>
<!ELEMENT FETT (#PCDATA | %TEXTFORMATIERUNGEN;)*>
<!ELEMENT ZEILENUMBRUCH EMPTY>
<!ELEMENT ZENTRIERT (#PCDATA | %TEXTFORMATIERUNGEN; | %GRAFIK;)*>
<!ELEMENT BILD (BILDURL, BILDNAME, BILDHOHE, BILDBREITE, BILDBESCHREIBUNG)>
<!ELEMENT BILDURL (#PCDATA)>
<!ELEMENT BILDNAME (#PCDATA)>
<!ELEMENT BILDHOHE (#PCDATA)>
<!ELEMENT BILDBREITE (#PCDATA)>
<!ELEMENT BILDBESCHREIBUNG (#PCDATA)>

=== nlsh/Kochbuch/xml/rezepte/backen/philadelphiaKaeseTorte.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE REZEPT SYSTEM "../../dtd_xsl/rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Philadelphia- K&#228;se- Torte</REZEPTNAME>
  <KATEGORIE>Backen</KATEGORIE>
  <AUTOR></AUTOR>
  <BEWERTUNG></BEWERTUNG>
  <ANZAHLPERSONEN></ANZAHLPERSONEN>
  <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>&#189; Wiener Boden ( auch ein anderer ist m&#246;glich)</ZUTAT>
    <ZUTAT>200 g Philadelphia Frischk&#228;se</ZUTAT>
    <ZUTAT>1 Tasse Zucker</ZUTAT>
    <ZUTAT>1 Zitrone</ZUTAT>
    <ZUTAT>1 P&#228;ckchen G&#246;tterspeise ( Zitronengeschmack)</ZUTAT>
    <ZUTAT>1 P&#228;ckchen Vanillezucker</ZUTAT>
    <ZUTAT>600 g s&#252;&#223;e Sahne</ZUTAT>
    <ZUTAT>2 Dosen Mandarinen</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Frischk&#228;se, Zucker, Zitronensaft, geriebene Zitronenschale und die
    Mandarinen ( ohne den Saft) gut verr&#252;hren</ITEM>
    <ITEM>eine Tasse Mandarinensaft mit einem P&#228;ckchen G&#246;tterspeise
    erw&#228;rmen- nicht kochen!!! und nach erkalten unterr&#252;hren</ITEM>
    <ITEM>als n&#228;chstes die Sahne steif schlagen und unterheben</ITEM>
    <ITEM>jetzt den Wiener Boden in eine Springform geben und die vorbereitete
    K&#228;semasse gleichm&#228;&#223;ig dar&#252;ber verteilen</ITEM>
    <ITEM>danach sofort in den K&#252;hlschrank</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/suppen/Kohlruebeneintopf.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE REZEPT SYSTEM "../../dtd_xsl/rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Kohlr&#252;beneintopf</REZEPTNAME>
  <KATEGORIE>Eintopf</KATEGORIE>
  <AUTOR>Mei&#223;ner, Christa</AUTOR>
  <BEWERTUNG>*****</BEWERTUNG>
  <ANZAHLPERSONEN></ANZAHLPERSONEN>
  <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>1 mittelgro&#223;e Kohlr&#252;be</ZUTAT>
    <ZUTAT>1 gro&#223;e M&#246;hre</ZUTAT>
    <ZUTAT>6 mittlere Kartoffeln</ZUTAT>
    <ZUTAT>1 kg Rindersuppenfleisch {optional &#252;ber Nacht gew&#228;ssertes
    P&#246;kelfleisch}</ZUTAT>
    <ZUTAT>3 Essl&#246;ffel Instant- Gem&#252;sebr&#252;he</ZUTAT>
    <ZUTAT>1 bis 2 Teel&#246;ffel Majoran</ZUTAT>
    <ZUTAT>&#188; Teel&#246;ffel Thymian</ZUTAT>
    <ZUTAT>1 Lorbeerblatt</ZUTAT>
    <ZUTAT>gemahlenen Pfeffer</ZUTAT>
    <ZUTAT>1 bis 2 Teel&#246;ffel Salz</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Fleisch in ca. anderthalb Liter Wasser mit der Instandbr&#252;he 2 Stunden
    kochen lassen und dann die Br&#252;he vom Fleisch trennen.</ITEM>
    <ITEM>Danach die gesch&#228;lte und in W&#252;rfeln geschnittene Kohlr&#252;be und
    M&#246;hre mit dem Lorbeerblatt in der Fleischbr&#252;he etwa 30 Minuten kochen
    lassen.</ITEM>
    <ITEM>Kartoffeln in nicht zuviel Salzwasser 20 Minuten mit dem Majoran und dem
    Thymian abkochen.</ITEM>
    <ITEM>Sind Kohlr&#252;ben sowie die Kartoffeln gar, beides mit den jeweiligen
    Fl&#252;ssigkeiten zusammenf&#252;gen und kurzstampfen.</ITEM>
    <ITEM>Das Fleisch in W&#252;rfel schneiden und unter die Kohlr&#252;ben
    mischen.</ITEM>
    <ITEM>Mit dem Pfeffer abschmecken - ist die Suppe zu dick, kann sie mit
    Gem&#252;sebr&#252;he verd&#252;nnt werden.</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/salate/kartoffelSalat.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE REZEPT SYSTEM "../../dtd_xsl/rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Kartoffelsalat</REZEPTNAME>
  <KATEGORIE>Kalte K&#252;che</KATEGORIE>
  <AUTOR>Christa Meissner</AUTOR>
  <BEWERTUNG>*****</BEWERTUNG>
 <ANZAHLPERSONEN></ANZAHLPERSONEN>
 <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>2,5 kg Kartoffeln ( festkochende)</ZUTAT>
    <ZUTAT>1 kleines Glas Mayonnaise</ZUTAT>
    <ZUTAT>1 Becher Schmand</ZUTAT>
    <ZUTAT>500 g Fleischsalat</ZUTAT>
    <ZUTAT>1 Essl&#246;ffel Salz</ZUTAT>
    <ZUTAT>Pfeffer</ZUTAT>
    <ZUTAT>1 Essl&#246;ffel Zucker</ZUTAT>
    <ZUTAT>Gurkenwasser mit etwas Essig</ZUTAT>
    <ZUTAT>Dill</ZUTAT>
    <ZUTAT>1 Teel&#246;ffel Senf</ZUTAT>
    <ZUTAT>Zwiebeln</ZUTAT>
    <ZUTAT>Apfel</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Kartoffeln sch&#228;len und kochen</ITEM>
    <ITEM>danach die Kartoffeln abk&#252;hlen lassen und in Scheiben schneiden</ITEM>
    <ITEM>jetzt das kleine Glas Mayonnaise, den Becher Schmand, den Fleischsalat, gehackte
    Zwiebeln und einen gew&#252;rfelten Apfel ( ohne Schale) dazugeben und das Ganze mit Salz,
    Pfeffer Gurkenwasser mit etwas Essig, Dill, sowie mit einem Teel&#246;ffel Senf nach
    eigenem Geschmack w&#252;rzen</ITEM>
    <ITEM>zum Schluss alles einen Tag k&#252;hl stehen lassen und fertig</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/backen/Waffeln.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE REZEPT SYSTEM "../Rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../Rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Waffeln</REZEPTNAME>
  <KATEGORIE>Backen</KATEGORIE>
  <AUTOR></AUTOR>
  <BEWERTUNG></BEWERTUNG>
  <ANZAHLPERSONEN></ANZAHLPERSONEN>
  <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>125 g Butter</ZUTAT>
    <ZUTAT>25 g Zucker</ZUTAT>
    <ZUTAT>1 P&#228;ckchen Vanillezucker</ZUTAT>
    <ZUTAT>abgeriebene Zitronenschale</ZUTAT>
    <ZUTAT>3 Eier</ZUTAT>
    <ZUTAT>250 g Mehl</ZUTAT>
    <ZUTAT>&#189; P&#228;ckchen Backpulver</ZUTAT>
    <ZUTAT>&#188; Liter Milch oder Sahne</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>die Butter schaumig r&#252;hren und Zucker, Vanillezucker, die geriebene
    Zitronenschale und die Eier dazugeben</ITEM>
    <ITEM>danach das mit Backpulver gemischte und gesiebte Mehl mit der Milch
    unterr&#252;hren, bis der Teig Blasen wirft</ITEM>
    <ITEM>als n&#228;chstes das Waffeleisen vorheizen und je nach Art des Waffeleisen
    dieses eventuell ein&#246;len</ITEM>
    <ITEM>beim abbacken nicht zuviel Teig in das Waffeleisen geben</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/suppen/Pizzasuppe.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE REZEPT SYSTEM "../Rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/Rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Pizzasuppe</REZEPTNAME>
  <KATEGORIE>Suppen</KATEGORIE>
  <AUTOR></AUTOR>
  <BEWERTUNG></BEWERTUNG>
 <ANZAHLPERSONEN></ANZAHLPERSONEN>
 <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>3 Dosen gesch&#228;lte Tomaten</ZUTAT>
    <ZUTAT>3 gelbe Paprikaschoten</ZUTAT>
    <ZUTAT>2 Stangen Porree</ZUTAT>
    <ZUTAT>750 ml Gem&#252;sebr&#252;he</ZUTAT>
    <ZUTAT>1 Glas Champignons ( 540g ) in Scheiben</ZUTAT>
    <ZUTAT>Salz und Pfeffer</ZUTAT>
    <ZUTAT>gerebelter Oregano</ZUTAT>
    <ZUTAT>250 g Kr&#228;uter- Schmelzk&#228;se</ZUTAT>
    <ZUTAT>&#189; Bund Basilikum</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Die Tomaten zusammen mit der Fl&#252;ssigkeit in einem gro&#223;en Topf geben,
    p&#252;rieren und durch ein Sieb streichen.</ITEM>
    <ITEM>Die Paprikaschoten halbieren, entstielen, entkernen, waschen und in Scheiben
    schneiden. Den Porree putzen, halbieren und in d&#252;nne Ringe schneiden.</ITEM>
    <ITEM>Die Paprikastreifen zusammen mit den Porreeringen zu den Tomaten geben und 10- 15
    min k&#246;cheln lassen.</ITEM>
    <ITEM>Danach die Br&#252;he und die Champignons hinzugeben und aufkochen lassen.</ITEM>
    <ITEM>Den Kr&#228;uter- Schmelzk&#228;se mit etwas Suppe glattr&#252;hren, dann unter die
    restliche Suppe r&#252;hren, erw&#228;rmen und mit Salz, Pfeffer und dem gerebelten
    Oregano abschmecken.
    <ZEILENUMBRUCH />
    <FETT>( Achtung ! ! ! Die Suppe darf jetzt nicht mehr kochen ! ! ! )</FETT></ITEM>
    <ITEM>Zum Schluss die abgesp&#252;lten und abgetrockneten Basilikumbl&#228;ttchen zerzupft
    auf die in Tellern servierte Suppe streuen.</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/backen/raffaelloTorte.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE REZEPT SYSTEM "../../dtd_xsl/rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Raffaello- Torte</REZEPTNAME>
  <KATEGORIE>Backen</KATEGORIE>
  <AUTOR></AUTOR>
  <BEWERTUNG>*****</BEWERTUNG>
  <ANZAHLPERSONEN></ANZAHLPERSONEN>
  <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>125 g Zucker</ZUTAT>
    <ZUTAT>125 g Butter</ZUTAT>
    <ZUTAT>100 g Mehl</ZUTAT>
    <ZUTAT>50 g Kokosraspeln</ZUTAT>
    <ZUTAT>1 P&#228;ckchen Vanillezucker</ZUTAT>
    <ZUTAT>4 Eier</ZUTAT>
    <ZUTAT>3 gestrichene Teel&#246;ffel Backpulver</ZUTAT>
    <ZUTAT>etwas Aprikosenmarmelade</ZUTAT>
    <ZUTAT>2- 3 Becher s&#252;&#223;e Sahne</ZUTAT>
    <ZUTAT>2- 3 P&#228;ckchen Sahnesteif</ZUTAT>
    <ZUTAT>12- 14 Raffaellos</ZUTAT>
    <ZUTAT>1 kleine Dose Aprikosen</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Kokosraspeln goldgelb r&#246;sten und abk&#252;hlen lassen</ITEM>
    <ITEM>Butter, Zucker, Vanillezucker und Eigelb schaumig r&#252;hren</ITEM>
    <ITEM>Kokosraspeln und Mehl daruntergeben und mit dem steif geschlagenen Eiwei&#223;
    mischen</ITEM>
    <ITEM>Teig in einer Springform ( &#248; 26 cm) bei 180&#186; Celsius 30 min
    backen</ITEM>
    <ITEM>Aprikosenmarmelade kurz erw&#228;rmen und auf den erkalteten Boden
    streichen</ITEM>
    <ITEM>jetzt die abgetropften Aprikosen dar&#252;berlegen</ITEM>
    <ITEM>Sahne mit Sahnesteif steif schlagen und zerkleinerte Raffaellos unter die Sahne
    mischen</ITEM>
    <ITEM>Sahne &#252;ber die Raffaellos streichen</ITEM>
    <ITEM>zum Schluss das Ganze mit halbierten Raffaellos verzieren</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/Gemuesebeilagen/Sauerkraut.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE REZEPT SYSTEM "../Rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../Rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Sauerkraut</REZEPTNAME>
  <KATEGORIE>Gem&#252;sebeilagen</KATEGORIE>
  <AUTOR>Mei&#223;ner, Christa</AUTOR>
  <BEWERTUNG>*****</BEWERTUNG>
  <ANZAHLPERSONEN>2</ANZAHLPERSONEN>
  <ZUBEREITUNGSZEIT>30 Minuten</ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>1 Beutel Sauerkraut, ca. 500 g</ZUTAT>
    <ZUTAT>&#189; Teel&#246;ffel Salz</ZUTAT>
    <ZUTAT>3- 4 Teel&#246;ffel Zucker</ZUTAT>
    <ZUTAT>1 Lorbeerblatt</ZUTAT>
    <ZUTAT>1 kleine Zwiebel</ZUTAT>
    <ZUTAT>&#189; Teel&#246;ffel K&#252;mmel</ZUTAT>
    <ZUTAT>1 Messerspitze gemahlenen Pfeffer</ZUTAT>
    <ZUTAT>2 Wacholderbeeren</ZUTAT>
    <ZUTAT>1 Teel&#246;ffel Margarine</ZUTAT>
    <ZUTAT>1 &#189; Tassen Wasser</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>alles
    <FETT>20 Minuten</FETT>&#160;bei &#246;fterem Umr&#252;hren kochen</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/salate/Gurkensalat.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE REZEPT SYSTEM "../Rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../Rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Gurkensalat</REZEPTNAME>
  <KATEGORIE>Salate</KATEGORIE>
  <AUTOR>Mei&#223;ner, Christa</AUTOR>
  <BEWERTUNG>*****</BEWERTUNG>
  <ANZAHLPERSONEN></ANZAHLPERSONEN>
  <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>eine mittelgro&#223;e Gurke</ZUTAT>
    <ZUTAT>&#188; kleine Zwiebel</ZUTAT>
    <ZUTAT>&#189; Teel&#246;ffel Salz</ZUTAT>
    <ZUTAT>2- 3 Teel&#246;ffel Zucker</ZUTAT>
    <ZUTAT>7 Teel&#246;ffel , 10% -tigen Essig</ZUTAT>
    <ZUTAT>&#189; Tasse Wasser</ZUTAT>
    <ZUTAT>Teel&#246;ffel Dill</ZUTAT>
    <ZUTAT>2 Prisen Pfeffer</ZUTAT>
    <ZUTAT>bis 5 Tropfen Oel { optional }</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Gurke in d&#252;nne Scheiben hobeln, Zwiebel in kleine W&#252;rfelchen
    schneiden.</ITEM>
    <ITEM>Die anderen Zutaten mit dem Wasser vermengen bis sich Zucker u. Salz
    aufgel&#246;st haben.</ITEM>
    <ITEM>Jetzt den Sud &#252;ber die Gurkenscheiben und Zwiebelw&#252;rfel gie&#223;en,
    alles gut vermengen.</ITEM>
    <ITEM>Schmeckt gut, wenn alles mindest &#189; Stunde zieht !</ITEM>
  </ZUBEREITUNG>
</REZEPT>
