=== nlsh/Kochbuch/xml/dtd_xsl/rezept.dtd
<!ENTITY % TEXTFORMATIERUNGEN "FETT | ZEILENUMBRUCH | ZENTRIERT">
<!ENTITY % GRAFIK "BILD">
<!ELEMENT REZEPT (REZEPTNAME, KATEGORIE, AUTOR, BEWERTUNG, ANZAHLPERSONEN, ZUBEREITUNGSZEIT, ZUTATEN, ZUBEREITUNG )>
<!ELEMENT REZEPTNAME (#PCDATA)>
<!ELEMENT KATEGORIE (#PCDATA)>
<!ELEMENT AUTOR (#PCDATA)>
<!ELEMENT BEWERTUNG (#PCDATA)>
<!ELEMENT ANZAHLPERSONEN (#PCDATA)>
<!ELEMENT ZUBEREITUNGSZEIT (#PCDATA)>
<!ELEMENT ZUTATEN (ZUTAT)+ >
<!ELEMENT ZUTAT (#PCDATA)>
<!ELEMENT ZUBEREITUNG (ITEM  | %GRAFIK;)+>
<!ELEMENT ITEM (#PCDATA | %TEXTFORMATIERUNGEN; | %GRAFIK;)*>
<!ELEMENT FETT (#PCDATA | %TEXTFORMATIERUNGEN;)*>
<!ELEMENT ZEILENUMBRUCH EMPTY>
<!ELEMENT ZENTRIERT (#PCDATA | %TEXTFORMATIERUNGEN; | %GRAFIK;)*>
<!ELEMENT BILD (BILDURL, BILDNAME, BILDHOHE, BILDBREITE, BILDBESCHREIBUNG)>
<!ELEMENT BILDURL (#PCDATA)>
<!ELEMENT BILDNAME (#PCDATA)>
<!ELEMENT BILDHOHE (#PCDATA)>
<!ELEMENT BILDBREITE (#PCDATA)>
<!ELEMENT BILDBESCHREIBUNG (#PCDATA)>

=== nlsh/Kochbuch/xml/rezepte/fleisch/haehnchenGeschnetzeltesStroganoff.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE REZEPT SYSTEM "../../dtd_xsl/rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>H&#228;hnchengeschnetzeltes Stroganoff</REZEPTNAME>
  <KATEGORIE>T&#246;pfe</KATEGORIE>
  <AUTOR></AUTOR>
  <BEWERTUNG></BEWERTUNG>
 <ANZAHLPERSONEN></ANZAHLPERSONEN>
 <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>1,2 kg H&#228;hnchenbrustfilet</ZUTAT>
    <ZUTAT>50 g Weizenmehl</ZUTAT>
    <ZUTAT>8 Essl&#246;ffel Speise&#246;l</ZUTAT>
    <ZUTAT>Salz und Pfeffer</ZUTAT>
    <ZUTAT>4 Zwiebeln</ZUTAT>
    <ZUTAT>2 Stangen Porree ( Lauch, 400 g)</ZUTAT>
    <ZUTAT>40 g Butter</ZUTAT>
    <ZUTAT>6 gro&#223;e Gew&#252;rzgurken</ZUTAT>
    <ZUTAT>250 ml ( &#188; l) Schlagsahne</ZUTAT>
    <ZUTAT>400 g Schmand</ZUTAT>
    <ZUTAT>100 ml Weiswein</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>H&#228;hnchenbrustfilet kurz unter flie&#223;endem kaltem Wasser absp&#252;len,
    trockentupfen, in Streifen schneiden und mit Mehl best&#228;uben.</ITEM>
    <ITEM>Etwas von dem &#214;l erhitzen, die Fleischstreifen in Portionen darin anbraten, mit
    Salz und Pfeffer bestreuen und herausnehmen.</ITEM>
    <ITEM>Zwiebeln abziehen, w&#252;rfeln und in dem verbliebenem Fett and&#252;nsten. Porree
    putzen, l&#228;ngst halbieren, waschen und in Streifen schneiden. Beides in dem
    verbliebenen Fett mit zerlassener Butter and&#252;nsten.</ITEM>
    <ITEM>Gurken in Streifen schneiden, mit Sahne und Schmand in einem gro&#223;en Topf
    mischen. Das Fleisch und Weiswein hineingeben und zum Kochen bringen. Mit Salz und Pfeffer
    abschmecken.</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/fleischgerichte/Boulettentopf.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE REZEPT SYSTEM "../../dtd_xsl/rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Bouletten Topf</REZEPTNAME>
  <KATEGORIE>Fleischgerichte</KATEGORIE>
  <AUTOR>Mei&#223;ner, Christa</AUTOR>
  <BEWERTUNG>*****</BEWERTUNG>
  <ANZAHLPERSONEN></ANZAHLPERSONEN>
  <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>1 kg Gehacktes</ZUTAT>
    <ZUTAT>3 Maggi fix f&#252;r Champignon</ZUTAT>
    <ZUTAT>1 Schlagsahne</ZUTAT>
    <ZUTAT>&#189; Becher saure Sahne</ZUTAT>
    <ZUTAT>1 gro&#223;e Dose Champignon on Saft</ZUTAT>
    <ZUTAT>1 kleine gew&#252;rfelte Zwiebel</ZUTAT>
    <ZUTAT>2- 3 Gew&#252;rzgurken</ZUTAT>
    <ZUTAT>als Beilage Reis, Kartoffeln, Brot, Nudeln...</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>1 kg Gehacktes wie in Boulettenmasse beschrieben w&#252;rzen</ITEM>
    <ITEM>aus der Masse kleine Bouletten krossig anbraten&gt;</ITEM>
    <ITEM>die 3 T&#252;ten Maggi fix nach Anleitung kochen</ITEM>
    <ITEM>dazu dann die Schlagsahne, den &#189; Becher saure Sahne, die Champignons ohne
    Saft und die Zwiebel hinzutun und alles zusammen aufkochen lassen</ITEM>
    <ITEM>zum Schluss die Bouletten hinzu und das Ganze einen Tag ziehen lassen</ITEM>
    <ITEM>als Beilage kann man dann Reis, Kartoffeln, Brot, Nudeln...w&#228;hlen</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/suppen/pikanteGyrosSuppe.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE REZEPT SYSTEM "../../dtd_xsl/rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Pikante Gyros- Suppe</REZEPTNAME>
  <KATEGORIE>Suppen</KATEGORIE>
  <AUTOR></AUTOR>
  <BEWERTUNG></BEWERTUNG>
 <ANZAHLPERSONEN></ANZAHLPERSONEN>
 <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>1,2 bis 1,5 kg Schweineschnitzel</ZUTAT>
    <ZUTAT>2 Knoblauchzehen</ZUTAT>
    <ZUTAT>8 EL &#214;l ( z.B. Oliven&#246;l</ZUTAT>
    <ZUTAT>1 bis 2 EL Gyros- Gew&#252;rzsalz</ZUTAT>
    <ZUTAT>300 g Schlagsahne</ZUTAT>
    <ZUTAT>3 Zwiebeln</ZUTAT>
    <ZUTAT>5 gro&#223;e Paprikaschoten ( 8 k&#246;nnen mehrfarbig sein)</ZUTAT>
    <ZUTAT>1 bis 2 EL Butter / Margarine</ZUTAT>
    <ZUTAT>2 Beutel ( a 30 g) Zwiebelsuppe ( f&#252;r &#190; l Fl&#252;ssigkeit)</ZUTAT>
    <ZUTAT>12 EL Zigeuner- oder Chili- Sauce</ZUTAT>
    <ZUTAT>150 g Sahne- Schmelzk&#228;se</ZUTAT>
    <ZUTAT>&#189; TL getrockneter Thymian</ZUTAT>
    <ZUTAT>Salz</ZUTAT>
    <ZUTAT>wei&#223;er Pfeffer</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Fleisch waschen, trockentupfen und in feine Streifen schneiden.
    <ZEILENUMBRUCH />Knoblauch sch&#228;len und hacken. Beides mit &#214;l und Gyros-
    Gew&#252;rzsalz verr&#252;hren. Zugedeckt 2- 3 Stunden in den K&#252;hlschrank
    stellen.</ITEM>
    <ITEM>Fleisch im W&#252;rz&#246;l portionsweise ca. 10 Minuten kr&#228;ftig braten.
    <ZEILENUMBRUCH />Dabei ab und zu wenden. Abk&#252;hlen lassen und die Sahne
    dar&#252;bergie&#223;en. Gyros zugedeckt &#252;ber Nacht kalt stellen.</ITEM>
    <ITEM>Zwiebeln sch&#228;len, in Ringe schneiden. Paprika putzen, waschen und in Streifen
    schneiden. Fett in einem gro&#223;en Topf erhitzen. Zwiebeln und Paprika darin
    and&#252;nsten. Mit 1 &#190; l Wasser abl&#246;schen. Aufkochen, Suppenpulver
    einr&#252;hren. Sauce, K&#228;se und Thymian einr&#252;hren. Ca. 10 Minuten k&#246;cheln
    lassen. Gyros in die Suppe geben. Alles nochmals gut durchkochen und abschmecken.</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/grill/grillschnitte.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE REZEPT SYSTEM "../Rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/Rezepte.xsl" ?>
<REZEPT>
 <REZEPTNAME>Grillschnitte</REZEPTNAME>
 <KATEGORIE>Auf dem Grill</KATEGORIE>
 <AUTOR>Anke Herrmann</AUTOR>
 <BEWERTUNG>*****</BEWERTUNG>
 <ANZAHLPERSONEN></ANZAHLPERSONEN>
 <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
 <ZUTATEN>
  <ZUTAT>Gehacktes, fertig gew&#252;rzt (siehe Boulettenmasse unter Fleischgerichte)</ZUTAT>
  <ZUTAT>Brot</ZUTAT>
 </ZUTATEN>
 <ZUBEREITUNG>
  <ITEM>Auf dem Brot das Gehaktes auftragen und dann auf dem Grill beidseitig grillen.</ITEM>
 </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/suppen/kurbisSuppe.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE REZEPT SYSTEM "../../dtd_xsl/rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Kürbis- Suppe</REZEPTNAME>
  <KATEGORIE>Suppen</KATEGORIE>
  <AUTOR>Nils Heinold</AUTOR>
  <BEWERTUNG>*****</BEWERTUNG>
 <ANZAHLPERSONEN>8</ANZAHLPERSONEN>
 <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>1 Hokaido- Kürbis, ca 1.000 g unausgenommen</ZUTAT>
    <ZUTAT>2 Esslöffel/ 30 g Butter</ZUTAT>
    <ZUTAT>500 ml Brühe</ZUTAT>
    <ZUTAT>2 Zwiebeln</ZUTAT>
    <ZUTAT>3- 4 cm Ingwer frisch</ZUTAT>
    <ZUTAT>1 Dose Mango, 400 g</ZUTAT>
    <ZUTAT>1 Dose Kokosmilch, 400 g</ZUTAT>
    <ZUTAT>1 Chilischote, rot, oder etwas Chilipulver</ZUTAT>
    <ZUTAT>eventuell Salz</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>den Kürbis und die Zwiebeln in Würfel schneiden und in der Butter anschmoren</ITEM>
    <ITEM>danach zusammen mit der Brühe, der Mango, der Kokosmilch und der geschälten und in Streifen geschnittenen Ingwer ca 20 min. köcheln lassen, bis der Kürbis weich zum pürieren ist</ITEM>
    <ITEM>das Ganze jetzt pürieren</ITEM>
    <ITEM>zum Schluss je nach Geschmack mit Chili abschmecken</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/suppen/Gehaltvolle_Soljanka.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE REZEPT SYSTEM "../Rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/Rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Gehaltvolle Soljanka</REZEPTNAME>
  <KATEGORIE>Suppen</KATEGORIE>
  <AUTOR>Mei&#223;ner, Christa</AUTOR>
  <BEWERTUNG>*****</BEWERTUNG>
  <ANZAHLPERSONEN></ANZAHLPERSONEN>
  <ZUBEREITUNGSZEIT>2 Stunden</ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>750 g Kasslerkamm</ZUTAT>
    <ZUTAT>250 g Dauerwurst, kleingew&#252;rfelt</ZUTAT>
    <ZUTAT>250 g Jagdwurst, kleingew&#252;rfelt</ZUTAT>
    <ZUTAT>1 Glas Letscho ( 720 ml)</ZUTAT>
    <ZUTAT>1 B&#252;chse passierte Tomaten ( 400 g)</ZUTAT>
    <ZUTAT>1 Glas roter Paprika mit Fl&#252;ssigkeit, kleingeschnitten ( 720 ml)</ZUTAT>
    <ZUTAT>5 feingeschnittene Gew&#252;rzgurken</ZUTAT>
    <ZUTAT>2 mittlere Zwiebeln, kleingew&#252;rfelt</ZUTAT>
    <ZUTAT>1 Lorbeerblatt</ZUTAT>
    <ZUTAT>2 Chilischoten, klein, getrocknet</ZUTAT>
    <ZUTAT>3 Pimentk&#246;rner</ZUTAT>
    <ZUTAT>10 Pfefferk&#246;rner</ZUTAT>
    <ZUTAT>3 Knoblauchzehen</ZUTAT>
    <ZUTAT>&#189; Liter Tomatensaft</ZUTAT>
    <ZUTAT>Tomatenketchup - ungew&#252;rzt ! ( 300- 400 g)</ZUTAT>
    <ZUTAT>2 Essl&#246;ffel dunklen Balsamico- Essig</ZUTAT>
    <ZUTAT>Salz, Chilipulver und Zucker zum Abschmecken</ZUTAT>
    <ZUTAT>Margarine zum Anbraten</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Kassler in 4 Tassen Wasser, eine der Zwiebeln, Lorbeerblatt, Chilischoten,
    Piment, Pfeffer, Knoblauch ansetzen und 1 &#189; Stunden kochen lassen. Die
    Dauerwurst die letzte halbe Stunde zugeben, Fleisch dann klein schneiden.</ITEM>
    <ITEM>Nach der Garzeit das Letscho, den Paprika, die Gurken, den Tomatensaft, die
    passierten Tomaten, Ketchup und den Balsamico unterr&#252;hren.</ITEM>
    <ITEM>Die Jagdwurstw&#252;rfel mit der anderen Zwiebel anbraten, alles dazugeben. Zum
    Schluss eventuell den gesamten Ansatz mit Wasser bis auf suppige Konsistenz
    verd&#252;nnen, mit
    <FETT>Zucker</FETT>, Salz und Chilipulver abschmecken</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/suppen/kartoffelSuppeMitAal.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE REZEPT SYSTEM "../../dtd_xsl/rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Kartofflesuppe mit Aal</REZEPTNAME>
  <KATEGORIE>Suppen</KATEGORIE>
  <AUTOR></AUTOR>
  <BEWERTUNG></BEWERTUNG>
 <ANZAHLPERSONEN></ANZAHLPERSONEN>
 <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>500 g Kartoffeln</ZUTAT>
    <ZUTAT>200 g Porree</ZUTAT>
    <ZUTAT>2- 3 TL Meerrettich naturell</ZUTAT>
    <ZUTAT>1 Becher Schlagsahne</ZUTAT>
    <ZUTAT>1 St&#252;ck R&#228;ucheraal</ZUTAT>
    <ZUTAT>Zitronensaft</ZUTAT>
    <ZUTAT>Salz und Pfeffer</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>Porree in Ringe schneiden und kurz and&#252;nsten</ITEM>
    <ITEM>Kartoffeln sch&#228;len und in St&#252;cke schneiden und in ca. 1 L Br&#252;he mit
    dem Porree gar kochen. Anschlie&#223;end alles mit dem Mixstab p&#252;rieren.</ITEM>
    <ITEM>Meerrettich unterr&#252;hren.</ITEM>
    <ITEM>R&#228;ucheraal enth&#228;uten und entgr&#228;ten und in St&#252;cke schneiden und
    ebenfalls unter die Suppe r&#252;hren.</ITEM>
    <ITEM>Die Schlagsahne unterheben und alles mit Salz, Pfeffer und Zitronensaft
    abschmecken.</ITEM>
  </ZUBEREITUNG>
</REZEPT>

=== nlsh/Kochbuch/xml/rezepte/backofen/eineKarreMist.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE REZEPT SYSTEM "../../dtd_xsl/rezept.dtd">
<?xml-stylesheet type="text/xsl" href="../../dtd_xsl/rezepte.xsl" ?>
<REZEPT>
  <REZEPTNAME>Eine Karre Mist</REZEPTNAME>
  <KATEGORIE>Backofen</KATEGORIE>
  <AUTOR></AUTOR>
  <BEWERTUNG></BEWERTUNG>
 <ANZAHLPERSONEN></ANZAHLPERSONEN>
 <ZUBEREITUNGSZEIT></ZUBEREITUNGSZEIT>
  <ZUTATEN>
    <ZUTAT>1 kg gew&#252;rztes Mett mit Zwiebeln</ZUTAT>
    <ZUTAT>3 gro&#223;e Tomaten</ZUTAT>
    <ZUTAT>1 gro&#223;e Dose Pilze</ZUTAT>
    <ZUTAT>1 Dose Mais</ZUTAT>
    <ZUTAT>200 g Gouda</ZUTAT>
    <ZUTAT>1 Becher Sahne</ZUTAT>
    <ZUTAT>3 TL Br&#252;he</ZUTAT>
    <ZUTAT>1 Schuss Wei&#223;wein</ZUTAT>
  </ZUTATEN>
  <ZUBEREITUNG>
    <ITEM>
      <ZENTRIERT>Kommt der Bauer sp&#228;t vom Feld ,
      <ZEILENUMBRUCH />die B&#228;uerin den Ofen anstellt.
      <ZEILENUMBRUCH />"Eine Karre Mist" hei&#223;t das Gericht,
      <ZEILENUMBRUCH />die Auflaufform h&#228;lt alles dicht.
      <ZEILENUMBRUCH />Ein Kilo Mett wird nun halbiert,
      <ZEILENUMBRUCH />damit man essen kann zu viert.
      <ZEILENUMBRUCH />Die H&#228;lfte kommt nun in die Form,
      <ZEILENUMBRUCH />das schmeckt bestimmt ganz enorm.
      <ZEILENUMBRUCH />Nun wird belegt mit den Tomaten
      <ZEILENUMBRUCH />Am besten aus dem eigenen Garten.
      <ZEILENUMBRUCH />Hinzu kommen Pilze und der Mais,
      <ZEILENUMBRUCH />am besten reicht man dazu Reis.
      <ZEILENUMBRUCH />Obenauf kommt noch mal Hack,
      <ZEILENUMBRUCH />damit der Bauer wird auch satt.
      <ZEILENUMBRUCH />Angegossen wird mit Sahne, Br&#252;he und Wein,
      <ZEILENUMBRUCH />nun kommt alles in den Ofen rein.
      <ZEILENUMBRUCH />Gebrutzelt wird bei 200 Grad,
      <ZEILENUMBRUCH />es schmeckt dann auch besonders zart,
      <ZEILENUMBRUCH />wenn man zum Schluss mit K&#228;s' es bedeckt,
      <ZEILENUMBRUCH />es sieht gut aus und schmeckt.</ZENTRIERT>
    </ITEM>
  </ZUBEREITUNG>
</REZEPT>
